# axios源码解读-取消请求

之前分析了,axios在请求开始前,也就是形成`axios`的`Promise`调用链完成初始化之前的全部流程

所以当我们使用axios,其实也就是执行promise执行链条,之前看了`请求拦截器` `接受拦截器`,但是最关键的地方也就是在`Axios`里面定义的请求序列组`dispatchRequest`,这才是才是执行请求的代码,所以今天看`dispatchRequest`内部的实现

`lib\core\dispatchRequest.js`

````javascript
/**
 * 如果已经请求取消，则抛出“取消”。
 */
function throwIfCancellationRequested(config) {
    // 当data里面存在cancelToken的时候,执行 config.cancelToken.throwIfRequested()这里断掉的请求
  if (config.cancelToken) {
    config.cancelToken.throwIfRequested()
  }
}

/**
 * 使用配置的服务器将配置发配到服务器
 *
 * @param {object} config 用于请求的配置
 * @returns {Promise} The Promise 执行 fulfilled
 */
module.exports = function dispatchRequest(config) {
  //取消请求
  throwIfCancellationRequested(config)
  
// ..............
````

可以看看官方的描述,取消请求有两种方式

**方式1**

```javascript
const source = axios.CancelToken.source()

axios(url, { cancelToken: source.token })
  .then(res => {
    console.log(res)
  })
  .catch(res => {
    console.log(res)
  })
source.cancel('Operation canceled by the user.')
```

方式2

```JavaScript
const CancelToken = axios.CancelToken
let cancel
console.log('请求开始前的准备个工作')
axios(url, {
  cancelToken: new CancelToken(function executor(c) {
    // 执行程序函数接收取消函数作为参数
    cancel = c
  })
})
.then(res => {
   console.log(res)
})
.catch(res => {
   console.log(res)
})

cancel('取消请求')
```

这里我分析第一种实现方式,因为这样的实现方式更加优雅

从第一条代码开始分析

```javascript
const source = axios.CancelToken.source()
```

从源文件圆口开始寻找

`lib\axios.js`

```js
// 取消请求的一些方法
axios.Cancel = require('./cancel/Cancel')
axios.CancelToken = require('./cancel/CancelToken')
axios.isCancel = require('./cancel/isCancel')
```

`lib\cancel\CancelToken.js`

```js
/**
 * 返回一个包含新的`CancelToken`的对象和一个被调用的函数
 * 取消`CancelToken`。
 */
CancelToken.source = function source() {
  var cancel;
  /**
   * 1. 根据官方的API 首先执行这个方法
   * 2. 将会的得到 CancelToken.executor里面的`cancel`方法 
   */
  var token = new CancelToken(function executor(c) {
    cancel = c;
  });
  console.log(token);
  return {
    token: token,
    cancel: cancel
  };
};
```

在里面返回了两个参数 一个是`token` 一个是`cancel`,token是`new CancelToken`的

```js
/**
 * " CancelToken "是一个可用于请求取消操作的对象。
 *
 * @class
 * @param {Function} 执行程序执行程序功能。

 */
function CancelToken(executor) {
  // 除了直接new CancelToken source方法也会走到这里
  /**
  * 判断execcutor是不是函数因为API里面有直接new的
  * 
  */
  if (typeof executor !== 'function') {
    throw new TypeError('executor must be a function.');
  }

  var resolvePromise;
  this.promise = new Promise(function promiseExecutor(resolve) {
    resolvePromise = resolve;
  });

  var token = this;
  // token里面现在有一个promise属性 但是未成功
  
  executor(function cancel(message) {
    // 这里的好像是为了防止data里面重复传值
    if (token.reason) {
      // 已经请求取消,将不会执行这个方法
      return;
    }
    console.log(resolvePromise);
    
    token.reason = new Cancel(message);

    resolvePromise(token.reason);
  });
   // 这个cancel函数就是 上面函数中的cancel，也就是source.cancel；
}
```

这里可以看到

cancel = CancelToken里面的executor()里面的cancel方法

token就是CancelToken,里面有一个promise对象

根据谷歌浏览器的调试,

```
1. 执行const source = axios.CancelToken.source()
2. axios进行初始化,同时 
source.cancel('Operation canceled by the user.')执行
```

注意 此时

```js
// score.cancel执行的时候就会自行 cancel的方法
function cancel(message) {
    // 这里的好像是为了防止data里面重复传值
    if (token.reason) {
      // 已经请求取消,将不会执行这个方法
      return;
    }    
    token.reason = new Cancel(message);
    // new Cancel在this上面添加了一个reason属性
    // 但是我看调试这段代码并没有执行
    resolvePromise(token.reason);
    // 
  }
```



于是在拦截器执行完成后,就是执行promise执行链条上面的`dispatchRequest`方法

````js
/**
 * 使用配置的服务器将配置发配到服务器
 *
 * @param {object} config 用于请求的配置
 * @returns {Promise} The Promise 执行 fulfilled
 */
module.exports = function dispatchRequest(config) {
  throwIfCancellationRequested(config)
// .......
}
````





````js
/**
 * 如果已经请求取消，则抛出“取消”。
 */
function throwIfCancellationRequested(config) {
  console.log(config.cancelToken)

  if (config.cancelToken) {
    config.cancelToken.throwIfRequested()
  }
}

````

当throwIfRequested执行的时候

````javascript
CancelToken.prototype.throwIfRequested = function throwIfRequested() {
  if (this.reason) {
    throw this.reason;
  }
};
````

明显,在axios的执行链条上面,抛出错误,进入`reject`状态

于是就会取消掉当前的请求操作